name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4  # ✅ Removed invalid working-directory
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website  # ✅ Correct usage

      - name: Build website
        run: yarn build
        working-directory: ./website  # ✅ Correct usage

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          branch: gh-pages  # ✅ Explicitly set the deployment branch
